version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "${{github.repository_owner}}"
    labels:
      - "dependencies"
      - "dependabot"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: auto
    # Security updates are enabled by default, no need for explicit flag 