name: Docs Ingestion

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'  # Only trigger on changes to docs directory
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/docsgpt
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  ingest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: docsgpt
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run docs ingestion
        run: pnpm docs:ingest 